# Generated by Django 5.2.3 on 2025-06-30 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('cash_adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('done_at', models.DateTimeField(auto_now_add=True)),
                ('offered_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_exchanges', to='listings.listing')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_exchanges', to='users.user')),
                ('requested_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_exchanges', to='listings.listing')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_exchanges', to='users.user')),
            ],
        ),
    ]
